config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  resources :animals
  resources :people
  resources :appointments
  resources :adoptions
  resources :shelters


  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
    validates :email, uniqueness: true

end 

app/models/adoption.rb
class Adoption <  ApplicationRecord

belongs_to :person 
belongs_to :animal

end

app/models/animal.rb
class Animal < ApplicationRecord

belongs_to :shelter 
has_many :people, through: :adoptions
has_many :adoptions 
has_many :appointments

validates :name, presence: true
validates :gender, presence: true
validates :breed, presence: true
validates :age, presence: true
validates :personality, presence: true


def self.not_adopted
    Animal.all.select do |animal|
    animal.adopted == false
    end
end


def change_adopt_status
    self.adopted = true 
end


end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

belongs_to :person, optional: true
belongs_to :shelter, optional: true
belongs_to :animal


end

app/models/person.rb
class Person < ApplicationRecord

has_many :adoptions
has_many :animals, through: :adoptions 
has_many :appointments
has_many :animals, through: :appointments 

validates :first_name, length: { minimum: 2 }
validates :last_name, presence: true
validates :email, presence: true
validates :email, uniqueness: true
validates :password, presence: true

has_secure_password 



end 

app/models/shelter.rb
class Shelter < ApplicationRecord

has_many :animals
has_many :appointments
has_many :people, through: :appointments

end 

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController

    def index
        @adoptions = Adoption.all
    end

    def show
        @adoption = Adoption.find(params[:id])
    end

    def new
        @adoption = Adoption.new
        @animal = Animal.find(params[:adoption][:animal_id])
    end

    def create
        @adoption = Adoption.new(animal_id: params[:adoption][:animal_id], person_id: params[:adoption][:person_id])
        @adoption.animal.change_adopt_status
        @adoption.animal.save
        
        if @adoption.save
            redirect_to animals_path
        else
            render new_adoption_path 
        end
    end


    def adoption_params
        params.require(:adoption).permit!
    end
end 

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

def index
    @animals = Animal.all
end

def show
    @animal = Animal.find(params[:id])
end

def new
    @animal = Animal.new
end 

def create
    @animal = Animal.new(animal_params)
    if @animal.valid?
       @animal.save
       redirect_to animal_path(@animal)
    else
        flash[:errors]= @animal.errors.full_messages
        redirect_to new_animal_path
    end
end

def edit
    @animal = Animal.find(params[:id])
end

def update
    @animal = Animal.find(params[:id])
    @animal.update(animal_params)
    redirect_to animal_path(@animal)
end 

def destroy 
    @animal.destroy
    redirect_to animal_path
end


def animal_params
    params.require(:animal).permit(:name, :age, :gender, :breed, :personality, :species, :shelter_id, :img_url)
end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def current_person
    Person.find_by(id:session[:id])
end

def logged_in?
    !!current_person
end

def not_logged_in
    redirect_to login_path unless logged_in?
end


end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    def index
        @appointments = Appointment.all
    end 

    def show
        @appointment = Appointment.find(params[:id])
    end

    def new 
        @appointment = Appointment.new
        @animal_id = params[:appointment][:animal_id]
    end

    def create
        @appointment = Appointment.new(date: params[:appointment][:date], time: params[:appointment][:time], shelter_id: 1, person_id: params[:appointment][:person_id], animal_id: params[:appointment][:animal_id])     
          if @appointment.save
            redirect_to person_path(@appointment.person)
        else
            render new_appointment_path
        end
    end
    
    def edit 
        @appointment = Appointment.find(params[:id])
    end

    def update
        @appointment = Appointment.find(params[:id])
        @appointment.update(appointment_params)
        redirect_to appointment_path
    end

    def destroy
        @appointment = Appointment.find_by(id: params[:id])
        @appointment.destroy
        redirect_to person_path(@appointment.person)
    end

    def appointment_params
        params.require(:appointment).permit!
    end
        
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

    before_action :not_logged_in, only: [:show]

    def new
        @person = Person.new
    end

    def show
        @person = Person.find(params[:id])
    end
    

    def create
    @person = Person.new(person_params)
    if @person.valid?
        @person.save
        session[:id] = @person.id 
        redirect_to person_path(@person)
    else 
        flash[:errors] = @person.errors.full_messages
        redirect_to new_person_path
    end 
    end 


    private 
    def person_params
        params.require(:person).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end 
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @person = Person.new
    end

    def create
        @person = Person.find_by(email: params[:person][:email])
        if @person && @person.authenticate(params[:person][:password])
            session[:id] = @person.id
            redirect_to person_path(@person)
        else
            flash[:errors] = ['Email or password is incorrect']
            redirect_to login_path
        end
    end 

    def destroy
        session.clear
        redirect_to login_path
    end
end 

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

    def show
        @shelter = Shelter.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adoptions/new.html.erb
<br>
<div class="text-center">

<h1 class='title-h1'> Adoption Confirmation </h1><hr/>

<%= form_for @adoption do |f| %>
   
    <h3>I am ready to take <%= @animal.name %> home with me! </h3> 
    <br>
      <%= f.hidden_field :person_id, value: session[:id] %>
     <h4><br><br>Once you confirm the adoption we will share the good news 
     and make sure to get everything ready for your arrival tomorrow at 5:00pm! <br><br>
    
        New Beginnings Shelter thanks you for making such a wonderful home for little <%= @animal.name %>. <br><br>See you soon! <br><br><br> </h4><br>

    <%= f.hidden_field :animal_id, value: @animal.id %>
    <button class="btn btn-success" type="submit">Please Confirm Adoption Here!</button>
</div>
    <%end%>

app/views/adoptions/show.html.erb
<h1> Adoption Show Page </h1>

Owner: <%=  @adoption.person.first_name %> <br><br>
Animal: <%= @adoption.animal.name %>

app/views/animals/_form.html.erb
<div class="text-center">
<ul>
<%= form_for @animal do |f| %>

    <h3><%=f.label :species %>: <br>
    <%= f.select :species, ['cat', 'dog']%><br><br>

    <%=f.label :name %>:<br>
    <%= f.text_field :name%><br><br>

    <%=f.label :age %>:<br>
    <%=f.select :age, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15']%>
    <br><br>

    <%=f.label :gender %>:<br>
    <%=f.select :gender, ['male', 'female']%><br><br>
    

    <%=f.label :breed %>:<br>
    <%=f.text_field :breed %><br><br>

    <%=f.label :personality %>: <br>
    <%=f.select :personality, ['friendly', 'energetic', 'laidback', 'shy', 'mischievous', 'playful']%>
   <br><br>

    <%=f.label :img_url %> (Optional Image Link)<br>
    <%=f.text_field :img_url%><br><br>

   <%= f.label :shelter_id %>: <br>
   <%= f.collection_select :shelter_id, Shelter.all, :id, :name%>
   <br><br>
    <%= f.submit%></h3>
    <%end %>
    </ul>
    </div>
   

app/views/animals/edit.html.erb
<br><h1> Edit Animal Form </h1> <hr/>
<%= render "form"%>

app/views/animals/index.html.erb
<br><br><br><br>
<div class="text-center">
<h1 class ='title-h1'> Meet Our New Beginnings Shelter Buddies! </h1> 

<br><br><br>
<h3> Available Dogs for Adoption </h3><br>
<% @animals.each do |animal| %>
    <% if animal.adopted == false && animal.species == "dog"%>
 <h2> <%= link_to animal.name, animal_path(animal), {:style=>'color:#006;', :class => "css_class"} %></h2>
 <%end%>
 <%end%>

</hr>

 <br><br><br><br>
 <h3> Available Cats for Adoption </h3><br>
<% @animals.each do |animal| %>
    <% if animal.adopted == false && animal.species == "cat"%>
 <h2> <%= link_to animal.name, animal_path(animal), {:style=>'color:#006;', :class => "css_class"}%></h2>
 <%end%>
 <%end%>

 <br><br>
 <h3> Check Out Our Adopted Pets! </h3>
 <% @animals.each do |animal| %>
    <% if animal.adopted%> 
    <h2> <%= link_to animal.name, animal_path(animal), {:style=>'color:#0077;', :class => "css_class"}%></h2>
 <%end%>
 <%end%>
 <br><br><br>
 <%= button_to "Log out", logout_path, method: :delete, class: 'btn btn-mini btn-danger' %>
 </div>
 <br>
   

app/views/animals/new.html.erb
<br><h1> New Animal Form </h1> <br><hr/>
<br>

<% if flash[:errors]%> 
<% flash[:errors].each do |message| %>
    <h3><li style= 'color:red'> <%= message %> </li></h3>
    <%end%>
    </ul>
    <%end%>
    <br>
<%= render "form"%>
   

app/views/animals/show.html.erb
<br>
<div class="text-center">

<h1 class ='title-h1'> Nice to meet you, call me <%=@animal.name%>!  </h1><hr/>

<br>

<img src= <%= @animal.img_url %> height="550" width="530"> <br><br>


<%if @animal.adopted %>
<h4><%= @animal.name%> was adopted by

<%= @animal.adoptions.first.person.first_name %> <%= @animal.adoptions.first.person.last_name %>
</h4>


<h3> I am grateful to now be at my furever home with my new family! <br>
Thank you for visiting our site so that my friends may also have the 
same opportunity as me! <br>
 They are all loyal and amazing pets who will make a great addition to any family! <br>
</h3><br>

<h2><%= link_to "Meet My Friends!", animals_path%></h2><br>

<%else%>

<h3> Hi there friend! Thank you so much for clicking on my name. 
Word is out that you're looking to adopt an adordable <%= @animal.species %>! 
<br>Well, look no more! <br>  
My name is <%= @animal.name %> and I am <%=@animal.age%> years old.<br>  
I am a <%=@animal.gender %> <%= @animal.breed %> breed who is known to be very <%= @animal.personality%>. <br> 
Can we play together soon? I hope to share my new life with you at my furever home! 
<br><br>
<u><b>Adoption Fee</u><b>: $<%=@animal.fee%></h3><br><br>

<h4>Schedule a Playdate with me! <br> <%= link_to "Appointment at Shelter", new_appointment_path(:appointment =>{:animal_id => @animal.id}), method: :get %></h4>
<br>
<h4>Let's go home!  <br><%= link_to "Adopt", new_adoption_path(:adoption => {:animal_id => @animal.id}), method: :get %></h4>
</div>
<br>
<h4>Meet my friends!  <br><%= link_to "See All Paws", animals_path%><br></h4><br><br><br>
<h5>Heartworm medication, updated vaccinations, paperwork and a toy are all included in the adoption fee</h5><br><br>

<%end%>

app/views/appointments/edit.html.erb
<div class="text-center">
<br><h1> Edit Your Playdate Appointment </h1>
<%= form_for @appointment do |f| %>
<br><br>
<h3>
    Please Select Day:
    <%=f.select :date, ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']%><br><br>

    <%=f.label :time %>:
    <%=f.select :time, ['12:00pm', '1:00pm', '2:00pm', '3:00pm', '4:00pm', '5:00pm', '6:00pm']%>
    <br><br><br>

    <%= f.submit 'Edit Appointment', class: 'btn btn-warning' %>
    <%end %>
    
    </div>
    </h3>
    

app/views/appointments/new.html.erb
<br>
<div class="text-center">
<h1 class ='title-h1'> Meet & Greet </h1><hr/>




<%= form_for @appointment do |f| %>

    <h3>Confirm <%=f.label :shelter_id%>: 
    <%=f.select :shelter, ['New Beginnings']%><br><br>

    Please Select Day:
    <%=f.select :date, ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']%><br><br>

    <%=f.label :time %>:
    <%=f.select :time, ['11:00am', '12:00pm', '1:00pm', '2:00pm', '3:00pm', '4:00pm', '5:00pm', '6:00pm']%>
    <br><br>

    <%= f.hidden_field :person_id, value: session[:id] %>
    <%= f.hidden_field :animal_id, value: @animal_id %>


    <button class="btn btn-success" type="submit">Create Appointment!</button>
    </h3>
    <%end %>
    </ul>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    

app/views/appointments/show.html.erb
<div class="text-center">
<br>
<h1 class='title-h1'> New Beginnings Scheduled Playdate  </h1>
<hr>


<h3><b> Shelter: New Beginnings </b><br><br>
Day of Appointment:  <b><%=  @appointment.date %></b> <br><br>
Time of Appointment: <b><%= @appointment.time %>:00am </b> <br><br><br><br>


<%= link_to "Edit Appointment", edit_appointment_path(@appointment), class: 'btn btn-mini btn-warning' %> <br><br>

<%= link_to "Delete Appointment", appointment_path(@appointment), method: :delete, data: { confirm: "Are you sure? Please don't go :(" }, class: 'btn btn-mini btn-danger' %> </h3>
</div>
<br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link href="style.css" text="text/css" rel="stylesheet" >

  <style>
  .nav-link {
    margin-left: 10px;
    # margin-right: 100px;
    font-size: 25px;
  }


</style>
</head>
<body>


    <title>PetsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <nav class="navbar navbar-expand-lg", style="background-color: #FFF;">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><%= image_tag '/images/logo.png', size: '150x80' %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" style="color: #000" aria-current="page" href="/people/<%= session[:id] %>">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="color: #000" href="/animals" >Animals</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="color: #000" href="/shelters/1">Contact Us</a>
            </li>
          </ul>
          <span class="navbar-text">
          </span>
        </div>
      </div>
    </nav>  

    <%= yield %>

    </div> 

  </body>
</html>

app/views/people/new.html.erb
<div class="text-center">
<br><h1> Create New Beginings Account </h1>
<br>

<% if flash[:errors]%> 
<% flash[:errors].each do |message| %>
    <h4 class="text-center" style= 'color:red'> <%= message %> </li></h4>
    <%end%>
    </ul>
    <%end%>
    <br>

    <%= form_for @person do |f| %>
    <h3><%= f.label :first_name %><br>
    <%= f.text_field :first_name %><br><br>

    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br><br>

    <%= f.label :email %><br>
    <%= f.text_field :email %><br><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br><br><br>

 <button class="btn btn-warning" style= 'color:white' type="submit">Create Account </button></h3>

</div>
    <%end%> 
    <br><br><br>

app/views/people/show.html.erb
<br>
<div class="text-center">
<div class='test-h3'><h1 class ='title-h1'> Welcome <%= @person.first_name%>!</h1> 

<hr/><br>

<br> <h3 class="first-h3"><br><br> We want to take a moment to thank you for creating an account and giving these animals the opportunity for a better life! <br><br>
New Beginnings provides shelter to thousands of animals annually, with the goal of placing all adoptable animals in their forever homes through adoption.
You can make appointments to come see our fur friend in person, but if it is love at first sight, you can go ahead and adopt right here on our website!<br><br>
We know they are all excited to meet you!<br><br><br></h3><br>
<h2> <%= link_to "All Paws", animals_path%></h2><br><br><br>


<h3 class="first-h3"> Your Upcomming Playdate Appointments: </h3><br>


<% @person.appointments.each do |app| %>

    <h4> <%= link_to app.animal.name , appointment_path(app) %> on <%= app.date %></h4>
    </div>
        <%end%>

         <br>




<br><br>
<%= link_to "Log out", logout_path, method: :delete, class: 'btn btn-mini btn-danger' %>
</div>
<br><br><br><br>

app/views/shelters/show.html.erb
<br>
<h1 class='title-h1'> Contact Us </h1><br><br><br>



<h3 class='font'><u>Shelter Name:</u><br> New Beginnings <br><br>
<u>Address:</u><br> <%= @shelter.address %> <br><br>
<u>Hours of business:</u><br> <%= @shelter.hours %> <br><br>
<u>Phone Number:</u><br> <%= @shelter.phone_number %></h3><br>